"""Backend contracts shared by embedded and future external implementations."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from m87_gateway.config import AppConfig


@runtime_checkable
class ConfigurationRepository(Protocol):
    def runtime_config(self) -> dict: ...
    def save_runtime_config(
        self, value: dict, provider=None, key=None, clear_key=False, **options
    ): ...
    def initialize_history(self, snapshot: dict) -> None: ...
    def list_config_revisions(self, limit: int = 100) -> list[dict]: ...
    def config_revision(self, revision_id: int) -> dict | None: ...


@runtime_checkable
class IdentityRepository(Protocol):
    def update_app_limits(self, app_id, rate_limit_per_minute, max_concurrent_requests): ...
    def create_app_key(
        self,
        app_id: str,
        allowed_models: list[str],
        capture_content: bool,
        rate_limit_per_minute: int | None = None,
        project_id: str = "default",
        max_concurrent_requests: int | None = None,
    ) -> tuple[dict[str, Any], str]: ...
    def issue_app_key(
        self, app_id: str, expires_in_days: int | None = None, revoke_existing: bool = False
    ): ...
    def list_app_keys(self, app_id: str) -> list[dict[str, Any]] | None: ...
    def revoke_app_key(self, app_id: str, key_id: str) -> bool: ...
    def authenticate_app_key(self, raw_key: str) -> AppConfig | None: ...
    def list_apps(self) -> list[dict[str, Any]]: ...
    def ensure_projects(self, identifiers: list[str]) -> None: ...
    def create_project(self, project_id: str, name: str) -> dict: ...
    def list_projects(self) -> list[dict]: ...
    def assign_app_project(self, app_id: str, project_id: str) -> bool: ...
    def delete_app(self, app_id: str) -> bool: ...
    def update_app_models(self, app_id: str, allowed_models: list[str]) -> bool: ...


@runtime_checkable
class SecretStore(Protocol):
    def put_provider_key(self, provider: str, value: str, alias: str = "default") -> None: ...
    def get_provider_key(self, provider: str, alias: str = "default") -> str | None: ...
    def list_provider_keys(self) -> list[dict[str, Any]]: ...
    def delete_provider_key(self, provider: str, alias: str = "default") -> bool: ...


@runtime_checkable
class TrafficRepository(Protocol):
    def emit(self, event: dict[str, Any]) -> None: ...
    def delete_events(self, project_id=None) -> int: ...
    def delete_content(self, project_id=None) -> int: ...
    def prune_events(self) -> int: ...
    def list_events(
        self,
        *,
        limit: int = 100,
        app_id: str | None = None,
        status: str | None = None,
        project_id: str | None = None,
        request_id: str | None = None,
        before: tuple[str, str] | None = None,
    ) -> list[dict[str, Any]]: ...
    def get_event(self, request_id: str) -> dict[str, Any] | None: ...
    def export_events(
        self, limit: int = 1000, project_id: str | None = None, **options
    ) -> list[dict[str, Any]]: ...


@runtime_checkable
class UsageRepository(Protocol):
    def overview(self, hours: int = 24, project_id: str | None = None) -> dict[str, Any]: ...
    def usage(self, hours: int = 24, project_id: str | None = None) -> dict: ...


@runtime_checkable
class ManagementAuditRepository(Protocol):
    def list_management_events(
        self, limit: int = 100, project_id: str | None = None
    ) -> list[dict[str, Any]]: ...
